# Generated by Django 3.0 on 2019-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191217_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_ids',
            field=models.ManyToManyField(blank=True, to='chat.User'),
        ),
    ]
