# Generated by Django 3.0 on 2019-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20191217_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_ids',
            field=models.ManyToManyField(to='chat.User'),
        ),
    ]
